#!/usr/bin/env python3
"""Turn the oracle binaries into the committed fixtures in ``../``.

Run ``make_lattice_oracle.sh`` first; this only reformats what it prints, so it
needs no CamCASP checkout of its own beyond the binaries that script built.

    ./make_fixtures.py [oracle-build]
"""
import pathlib
import subprocess
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
BUILD = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "oracle-build"
DATA = HERE.parent

# Seeds spanning what CamCASP documents as the legal range, plus 0 (which is
# what an unseeded run gets) and 9999 (the top of it).
SEEDS = [0, 1, 7, 9999]

# Enough draws to wrap the 101-element lag table several times.
NDRAW = 256

# Sparse checkpoints far out in the stream, so a lag-index bug that only shows
# up after many wraps cannot hide behind a short prefix.
CHECKPOINTS = [1000, 10000, 100000]

# Molecules: water for the three-atom centre-of-geometry arithmetic, HCl for a
# second van der Waals radius and a badly off-centre cube.
MOLECULES = {
    "h2o": [(8.0, 0.0, 0.0, -0.12425761),
            (1.0, 0.0, -1.43191407, 0.98633103),
            (1.0, 0.0, 1.43191407, 0.98633103)],
    "hcl": [(17.0, 0.0, 0.0, 0.0),
            (1.0, 0.0, 0.0, 2.40862)],
}


def prand(seed, n):
    out = subprocess.run([BUILD / "pranddump"], input=f"{seed} {n}\n",
                         capture_output=True, text=True, check=True).stdout
    return [line.split()[1] for line in out.splitlines()]


def lattice(atoms, seed, npoints, lolim, hilim):
    inp = [f"{seed} {npoints} {lolim} {hilim}", str(len(atoms))]
    inp += [f"{z} {x!r} {y!r} {zz!r}" for z, x, y, zz in atoms]
    out = subprocess.run([BUILD / "latticedump"], input="\n".join(inp) + "\n",
                         capture_output=True, text=True, check=True).stdout.splitlines()
    centre = np.array([float(v) for v in out[0].split()[1:]])
    dmax = float(out[1].split()[1])
    pts = np.array([[float(v) for v in line.split()[1:]] for line in out[3:]])
    return centre, dmax, pts


with open(DATA / "camcasp_prand.dat", "w") as fh:
    fh.write("# CamCASP src/random.f90, Maclaren (1992) sdprnd/dprand.\n")
    fh.write("# Generated by oracle/make_fixtures.py; see oracle/README.md.\n")
    fh.write(f"# stream: seed  i  dprand()   (i = 1 ... {NDRAW}, after sdprnd(seed))\n")
    fh.write("# check:  seed  i  dprand()   (the i-th draw of the same stream)\n")
    for seed in SEEDS:
        for i, v in enumerate(prand(seed, NDRAW), start=1):
            fh.write(f"stream {seed:5d} {i:6d}  {v}\n")
    for n in CHECKPOINTS:
        for seed in SEEDS:
            fh.write(f"check  {seed:5d} {n:6d}  {prand(seed, n)[-1]}\n")

arrays = {}
for name, atoms in MOLECULES.items():
    centre, dmax, pts = lattice(atoms, seed=1, npoints=2000, lolim=2.0, hilim=4.0)
    arrays[f"{name}_geom"] = np.array(atoms)
    arrays[f"{name}_centre"] = centre
    arrays[f"{name}_dmax"] = dmax
    arrays[f"{name}_points"] = pts
np.savez_compressed(DATA / "camcasp_fit_points.npz", **arrays)

print(f"wrote {DATA / 'camcasp_prand.dat'} and {DATA / 'camcasp_fit_points.npz'}")
