#!/usr/bin/env python3
"""Parse CamCASP's generated dispersion-recoupling tables.

`src/casimir/c6code.f90 ... c12code.f90` are machine-generated Fortran fragments,
`INCLUDE`d into `SUBROUTINE ccalc` (casimir.f90).  Each names one block

    !  L1=<L1>, L2=<L2>, J=<J>
    do t=<lo>,<hi>            ! or `t=1` when L1 = 0
      do u=<lo>,<hi>
        C(n,t,u,J) = <term> [& <term> ...]
      end do
    end do

and each term is

    <sign> [<p>d0 | (<p>d0/<q>d0)] [* sqrt(<r>d0[/<s>d0])] * cpint(a,t,la,la', b,u,lb,lb', ip)

The coefficient never depends on t or u -- only on (n, L1, L2, J) and which term
of the block it is -- so the whole of the seven files reduces to a list of

    (n, L1, L2, J) -> [(p, q, r, s, la, la', lb, lb', ip), ...]

with the coefficient the exact root-rational fraction (p/q) sqrt(r/s), the sign
carried in p, and `ip` the power of i to fold in.  That is what this script emits.

It writes two files, and is the only thing that ever reads CamCASP for them:

  * `../camcasp_recoupling.dat`, the committed fixture `test_isapol.py` holds
    `libisapol` to;
  * `psi4/src/psi4/libisapol/recoupling_data.inc`, the generated table that
    `recoupling_tables.cc` compiles in.

Both are committed, so a CamCASP checkout is needed only to regenerate them.

Usage:  CAMCASP=~/gits/CamCASP ./parse_cncode.py
"""

import os
import re
import sys
from fractions import Fraction

CAMCASP = os.path.expanduser(os.environ.get("CAMCASP", "~/gits/CamCASP"))
SRC = os.path.join(CAMCASP, "src", "casimir")

BLOCK = re.compile(r"^!\s*L1=(\d+),\s*L2=(\d+),\s*J=(\d+)\s*$")
LOOP = re.compile(r"^\s*(?:do\s+)?([tu])\s*=\s*(\d+)\s*(?:,\s*(\d+)\s*)?$")
ASSIGN = re.compile(r"^\s*C\((\d+),t,u,(\d+)\)\s*=\s*(.*)$")

# <sign> <rational> <sqrt> cpint(a,t,la,lap, b,u,lb,lbp, ip)
TERM = re.compile(
    r"([+-])\s*"
    r"(?:\(\s*(\d+)d0\s*/\s*(\d+)d0\s*\)|(\d+)d0)?\s*\*?\s*"
    r"(?:sqrt\(\s*(\d+)d0\s*(?:/\s*(\d+)d0\s*)?\)\s*\*\s*)?"
    r"cpint\(a,t,(\d+),(\d+),\s*b,u,(\d+),(\d+),\s*(\d+)\)"
)


def rank_range(L):
    """Component indices of rank L, 1-based, in CamCASP's 00 10 11c 11s 20 ... order."""
    return (L * L + 1, (L + 1) * (L + 1))


def parse(n):
    """Return {(L1, L2, J): [term, ...]} for one c<n>code.f90."""
    path = os.path.join(SRC, "c%dcode.f90" % n)
    with open(path) as fh:
        # Fortran line continuations: fold `&`-terminated lines into their successor.
        text = re.sub(r"&\s*\n\s*", " ", fh.read())

    blocks = {}
    key = None
    trange = urange = None
    for line in text.splitlines():
        m = BLOCK.match(line)
        if m:
            key = tuple(int(g) for g in m.groups())
            trange = urange = None
            continue
        m = LOOP.match(line)
        if m and "C(" not in line:
            lo = int(m.group(2))
            hi = int(m.group(3)) if m.group(3) else lo
            if m.group(1) == "t":
                trange = (lo, hi)
            else:
                urange = (lo, hi)
            continue
        m = ASSIGN.match(line)
        if not m:
            continue
        nn, J, rhs = int(m.group(1)), int(m.group(2)), m.group(3)
        assert nn == n, (n, line)
        L1, L2, JJ = key
        assert J == JJ, (key, line)
        # The loop bounds must be exactly the component range of each rank: that
        # is the assumption that lets us store one term list per (L1, L2, J).
        assert trange == rank_range(L1), (key, trange)
        assert urange == rank_range(L2), (key, urange)

        terms = []
        pos = 0
        for t in TERM.finditer(rhs):
            assert t.start() == pos or rhs[pos:t.start()].strip() == "", rhs[pos:t.start()]
            pos = t.end()
            sign, pn, qn, whole, r, s, la, lap, lb, lbp, ip = t.groups()
            p = Fraction(int(pn), int(qn)) if pn else Fraction(int(whole) if whole else 1)
            if sign == "-":
                p = -p
            rr = Fraction(int(r), int(s) if s else 1) if r else Fraction(1)
            la, lap, lb, lbp, ip = (int(x) for x in (la, lap, lb, lbp, ip))
            assert la + lap + lb + lbp + 2 == n, (n, la, lap, lb, lbp)
            assert abs(L1 - L2) <= J <= L1 + L2, (key,)
            terms.append((p, rr, la, lap, lb, lbp, ip))
        assert rhs[pos:].strip() == "", rhs[pos:]
        assert terms, line
        assert key not in blocks, key
        blocks[key] = terms
    return blocks


HERE = os.path.dirname(os.path.abspath(__file__))
DAT = os.path.join(HERE, os.pardir, "camcasp_recoupling.dat")
INC = os.path.join(HERE, *([os.pardir] * 4), "psi4", "src", "psi4", "libisapol",
                   "recoupling_data.inc")

BANNER = """\
// Generated by tests/pytests/data_isapol/oracle/parse_cncode.py from CamCASP's
// src/casimir/c6code.f90 ... c12code.f90.  Do not edit; see SPEC.md 9.3 and
// recoupling_tables.h for what the numbers mean.
"""


def write_dat(table):
    with open(DAT, "w") as out:
        out.write("# CamCASP dispersion recoupling coefficients, parsed from\n")
        out.write("# src/casimir/c{6..12}code.f90 by oracle/parse_cncode.py.\n")
        out.write("#\n")
        out.write("# block n L1 L2 J nterms\n")
        out.write("#   p q r s la lap lb lbp ip   -- coefficient (p/q) sqrt(r/s), times i^ip\n")
        for (n, L1, L2, J), terms in table:
            out.write("block %d %d %d %d %d\n" % (n, L1, L2, J, len(terms)))
            for p, r, la, lap, lb, lbp, ip in terms:
                out.write("  %d %d %d %d %d %d %d %d %d\n"
                          % (p.numerator, p.denominator, r.numerator, r.denominator,
                             la, lap, lb, lbp, ip))


def write_inc(table):
    nterm = sum(len(t) for _, t in table)
    with open(INC, "w") as out:
        out.write(BANNER)
        out.write("\nconstexpr int kNumRecouplingBlocks = %d;\n" % len(table))
        out.write("constexpr int kNumRecouplingTerms = %d;\n\n" % nterm)
        out.write("const RecouplingTerm kRecouplingTerms[kNumRecouplingTerms] = {\n")
        for (n, L1, L2, J), terms in table:
            out.write("    // C%d  L1=%d L2=%d J=%d\n" % (n, L1, L2, J))
            for p, r, la, lap, lb, lbp, ip in terms:
                out.write("    {%d, %d, %d, %d, %d, %d, %d, %d, %d},\n"
                          % (p.numerator, p.denominator, r.numerator, r.denominator,
                             la, lap, lb, lbp, ip))
        out.write("};\n\n")
        out.write("// Sorted on `key`, so recoupling_block() can bisect.\n")
        out.write("const RecouplingBlockRecord kRecouplingBlocks[kNumRecouplingBlocks] = {\n")
        first = 0
        for (n, L1, L2, J), terms in table:
            out.write("    {%d, %d, %d, %d, %d, %d},\n"
                      % (n, L1, L2, J, first, len(terms)))
            first += len(terms)
        out.write("};\n")


def main():
    table = []
    for n in range(6, 13):
        for key, terms in sorted(parse(n).items()):
            table.append(((n,) + key, terms))
    keys = [k for k, _ in table]
    assert keys == sorted(keys)
    write_dat(table)
    write_inc(table)
    sys.stderr.write("%d blocks, %d terms\n"
                     % (len(table), sum(len(t) for _, t in table)))


if __name__ == "__main__":
    main()
