#!/usr/bin/env python3
"""Run the C++ ISA-A controller from a captured initial exported-input state.

Unlike transition replay, intermediate shapes/tails are generated by C++. Basis,
fixed Drho-C coefficients, geometry and quadrature still come from the reference.
Convergence is not an end-to-end/native-generation or reference-parity certificate.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import time
import numpy as np

spec = importlib.util.spec_from_file_location('sweep_replay', Path(__file__).with_name('replay_isa_sweep.py'))
sweep = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sweep)


def run(directory):
    import psi4
    started = time.perf_counter()
    provenance = {}
    for path in [Path(psi4.core.__file__), Path(__file__), Path(sweep.__file__),
                 Path(directory)/'isapol-sweep-state.dat']:
        with path.open('rb') as handle:
            provenance[str(path)] = hashlib.file_digest(handle, 'sha256').hexdigest()
    controller, initial, checkpoints, state = sweep.prepare_replay(directory)
    if state['iteration'] != 1 or initial.iteration != 0:
        raise ValueError('Full trajectory requires the captured initial sweep')
    prepared = time.perf_counter()
    result = controller.run(initial)
    elapsed = time.perf_counter()-prepared
    final = result.state
    tail_input = result.history[-2].next if len(result.history) > 1 else initial
    def tail(t):
        return dict(defined=t.defined, amplitude=t.amplitude, exponent=t.exponent, cutoff=t.cutoff)
    history = []
    for step in result.history:
        history.append(dict(iteration=step.next.iteration, max_delta=step.next.max_delta,
            deltas=step.deltas, converged=step.next.converged, atom_converged=step.atom_converged,
            active_w_eps=step.next.active_w_eps, active_positive_lambda=step.next.active_positive_lambda,
            apply_tails=step.next.apply_tails, shape_charges=step.shape_charges,
            populations=[f.population for f in step.raw_sweep.fits],
            residuals=[f.relative_residual for f in step.raw_sweep.fits],
            excluded_points=[f.excluded_points for f in step.raw_sweep.fits],
            tail_status=[f.status for f in step.tail_fits]))
    return dict(schema_version=1,
        evidence_class='C++ controller trajectory from exported initial bases/density/grids; not end-to-end parity',
        limitations=['No intermediate shape/tail injection after initialization',
                     'Native basis recipe, SCF and Drho-C generation remain absent',
                     'Reference final-state comparison is a separate required measurement',
                     'Deterministic tail policy omits legacy stale-A gate and undefined IP'],
        termination=result.termination, converged=final.converged, iterations=final.iteration,
        preparation_seconds=prepared-started, controller_seconds=elapsed,
        psi4_extension=psi4.core.__file__, entry_sha256=provenance,
        initial_checkpoint_sha256={f'isapol-atom-{a+1}.dat': hashlib.sha256((Path(directory)/f'isapol-atom-{a+1}.dat').read_bytes()).hexdigest() for a in range(3)},
        final_tail_input=dict(iteration=tail_input.iteration,
            shape_coefficients=tail_input.coefficients.shape_coefficients,
            tails=[tail(t) for t in tail_input.tails]),
        final=dict(atomic_coefficients=final.coefficients.atomic_coefficients,
                   shape_coefficients=final.coefficients.shape_coefficients,
                   tails=[tail(t) for t in final.tails], saved_shape_charges=final.saved_shape_charges,
                   active_w_eps=final.active_w_eps, active_positive_lambda=final.active_positive_lambda,
                   apply_tails=final.apply_tails, max_delta=final.max_delta), history=history)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    parser.add_argument('--report', type=Path, required=True)
    args = parser.parse_args()
    if args.report.exists():
        raise FileExistsError(f'Refusing to overwrite trajectory report {args.report}')
    report = run(args.directory)
    args.report.write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps({k:report[k] for k in ['termination','converged','iterations','controller_seconds']}, indent=2))
    if not report['converged']:
        raise SystemExit('C++ controller did not converge; report retained')
